### ISSUE TITLE
Large cluster: multus-admission-controller load on kube-apiserver causing instability on restart

### ISSUE THREAD

**Issue by rgschofield** [openshift/multus-admission-controller#40]
We have a 225 node Openshift 4.8 cluster with an average of around 60 pods running on each node.
The cluster's kube-apiservers are running on three 16x64 nodes in a multi-zone setup.
We triggered a restart of the kube-apiservers to simulate a failure situation. Then the fun began!

Following the restart, we observed that all kube-apiservers entered a sustained period of continual restarts due to OOM events. 
Looking at the kube-apiserver logs for the cluster we saw a number of entries similar to
```
I1123 16:53:52.186094       1 trace.go:205] Trace[55581488]: "List" url:/api/v1/pods,user-agent:webhook/v0.0.0 (linux/amd64) kubernetes/$Format,audit-id:f8ea4f7f-f25d-4853-8259-0d71264c2cc6,client:172.18.84.192,accept:application/json, */*,protocol:HTTP/2.0 (23-Nov-2021 16:52:54.920) (total time: 57265ms):
E1123 16:53:52.190684       1 timeout.go:135] post-timeout activity - time-elapsed: 1m59.888785673s, GET "/api/v1/pods" result: <nil>
E1123 16:53:52.221192       1 timeout.go:135] post-timeout activity - time-elapsed: 54.109753838s, GET "/api/v1/namespaces/master-rgshc5-1-10/pods/etcd-operator-8f6d8bd84-qwv2v" result: <nil>
I1123 16:53:52.236883       1 trace.go:205] Trace[1396252026]: "SerializeObject" method:GET,url:/api/v1/pods,protocol:HTTP/2.0,mediaType:application/json,encoder:{"encodeGV":"v1","encoder":"{\"name\":\"json\",\"pretty\":\"false\",\"yaml\":\"false\"}","name":"versioning"} (23-Nov-2021 16:53:03.077) (total time: 49159ms):
```
We also saw requests to etcd with fairly sizeable responses in the etcd logs as follows:
```
2021-11-23 16:54:11.203549 W | etcdserver: read-only range request "key:\"/kubernetes.io/pods/\" range_end:\"/kubernetes.io/pods0\" " with result "range_response_count:16736 size:138527833" took too long (135.980253ms) to execute
2021-11-23 16:54:11.927551 W | etcdserver: read-only range request "key:\"/kubernetes.io/pods/\" range_end:\"/kubernetes.io/pods0\" " with result "range_response_count:16736 size:138527503" took too long (139.268151ms) to execute
2021-11-23 16:54:12.519189 W | etcdserver: read-only range request "key:\"/kubernetes.io/pods/\" range_end:\"/kubernetes.io/pods0\" " with result "range_response_count:16736 size:138528022" took too long (140.033626ms) to execute
```
The chart below shows the cpu utilzation on the nodes running the kube-apiserver and etcd workload for the cluster. The spikes in utilzation demonstrate the restarts of the kube-apiservers. Only when the _multus-admission-controller_ pods were disabled, did we see a return to a stable environment

![kas-restarts](https://user-images.githubusercontent.com/20518471/145560066-af4cd1c0-3ef0-47a1-829d-1b730c2659ec.png)

Will also look to see to what extent it's possible to mitigate the impact of this issue using the API Priority and Fairness feature

**Comment by relyt0925** [comment]
The API Priority and fairness rule did mitigate the load

**Comment by relyt0925** [comment]
```
apiVersion: "flowcontrol.apiserver.k8s.io/v1beta1"
kind: FlowSchema
metadata:
  name: multus-service-account
spec:
  distinguisherMethod:
    type: ByNamespace
  matchingPrecedence: 2
  priorityLevelConfiguration:
    name: openshift-multus
  rules:
    - nonResourceRules:
        - nonResourceURLs:
            - '*'
          verbs:
            - '*'
      resourceRules:
        - apiGroups:
            - '*'
          clusterScope: true
          namespaces:
            - '*'
          resources:
            - '*'
          verbs:
            - '*'
      subjects:
        - kind: ServiceAccount
          serviceAccount:
            name: '*'
            namespace: openshift-multus
```


```
apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  name: openshift-multus
spec:
  limited:
    assuredConcurrencyShares: 1
    limitResponse:
      type: Reject
  type: Limited
```

**Comment by relyt0925** [comment]
[Armada_Perf_Update_24Jan22.pdf](https://github.com/openshift/multus-admission-controller/files/7965265/Armada_Perf_Update_24Jan22.pdf)

**Comment by mcginne** [comment]
We have been running further tests in this area and still seeing issues.

This time with a 500 node cluster - but it has very little running on it. If we kill the apiservers then we see a spike in memory, then one of the apiservers runs at 100% CPU for around 6 minutes, in the logs we see the requests reported above:

<img width="1498" alt="image" src="https://user-images.githubusercontent.com/27362732/178737434-817c0532-7cf6-43a4-94ea-b0e6ca18d5aa.png">

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/27362732/178737514-45d5defa-8852-4f72-9683-6fdc10b2447b.png">

(These are 16core x 64GB nodes)
Apiserver logs show lots of requests such as these, and they stop at the same time as we see the CPU drop back down:
```
I0712 12:19:22.690155       1 panic.go:965] "HTTP" verb="LIST" URI="/api/v1/pods?limit=500&resourceVersion=0" latency="1m0.023443627s" userAgent="webhook/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="3cf7e40e-7a66-4b56-81d7-51075bc67e9f" srcIP="172.18.252.192:14385" resp=200
I0712 12:19:22.744884       1 trace.go:205] Trace[1893591201]: "List" url:/api/v1/pods,user-agent:webhook/v0.0.0 (linux/amd64) kubernetes/$Format,audit-id:3cf7e40e-7a66-4b56-81d7-51075bc67e9f,client:172.18.252.192,accept:application/json, */*,protocol:HTTP/2.0 (12-Jul-2022 12:18:22.669) (total time: 60075ms):
I0712 12:19:22.806327       1 panic.go:965] "HTTP" verb="LIST" URI="/api/v1/pods?limit=500&resourceVersion=0" latency="1m0.085285692s" userAgent="webhook/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="a6d9d022-70c2-477a-8c80-c913c998e2c3" srcIP="10.95.174.250:3198" resp=200
```

When we applied the API Priority & Fairness rule above it changes the behaviour - but it is still not ideal. The memory does not grow anywhere near as high - but the CPU spike goes on for 1hour 40 mins!

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/27362732/178738030-7e38f89c-4f33-4bf3-bfd3-f26af4318814.png">
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/27362732/178738130-ae4e21b5-7dd7-4b04-9b28-3c30eacbfcfd.png">

The logs from this run were even more interesting! I see lots of the requests get `429` responses - presumably that's the APF rules kicking in - but the rate of these requests is pretty high - so I think it is retrying when it gets a 429 with no backoff, so by applying the APF rule it has made things worse, as it is just continually retrying!

I can also see the following in the logs, which suggests a lot of the time is spent building the response as json, and then transmitting it:

```
I0712 15:46:42.268934       1 trace.go:205] Trace[2000016074]: "SerializeObject" method:GET,url:/api/v1/pods,protocol:HTTP/2.0,mediaType:application/json,encoder:{"encodeGV":"v1","encoder":"{\"name\":\"json\",\"pretty\":\"false\",\"yaml\":\"false\"}","name":"versioning"} (12-Jul-2022 15:46:29.448) (total time: 12820ms):
Trace[2000016074]: ---"About to start writing response" size:65046394 7063ms (15:46:36.511)
Trace[2000016074]: ---"Write call finished" writer:*gzip.Writer,size:65046394,firstWrite:true 5735ms (15:46:42.246)
Trace[2000016074]: [12.820724167s] [12.820724167s] END
I0712 15:46:42.269284       1 trace.go:205] Trace[887908279]: "List" url:/api/v1/pods,user-agent:webhook/v0.0.0 (linux/amd64) kubernetes/$Format,audit-id:d01f6c88-03a4-4bb3-ad1b-6e966dcd6a84,client:172.18.84.192,accept:application/json, */*,protocol:HTTP/2.0 (12-Jul-2022 15:46:29.414) (total time: 12854ms):
Trace[887908279]: ---"Writing http response done" count:6474 12820ms (15:46:42.269)
Trace[887908279]: [12.854071717s] [12.854071717s] END
```
Full logs from APF run ->
[high_cpu_APF.log.zip](https://github.com/openshift/multus-admission-controller/files/9102327/high_cpu_APF.log.zip)

If you do `grep /api/v1/pods high_cpu_APF.log | grep webhook` you will see the large number of requests.

I think there are a few questions here:

1. Do the multus admission-controller pods need to get the full list of pods, as this can be a very expensive query on large clusters - especially from a daemonset!
2. Can it at least do some backoffs on this request if it gets errors back.

**Comment by mcginne** [comment]
When we disabled multus pods using:
```
kubectl scale deploy -n openshift-network-operator                         network-operator  --replicas=0
kubectl -n openshift-multus patch daemonset multus-admission-controller -p '{"spec": {"template": {"spec": {"nodeSelector": {"non-existing": "true"}}}}}'
```
we were able to restart the apiservers with barely a blip on the CPU chart, and a significant reduction in memory usage.

**Comment by relyt0925** [comment]
@dougbtv stated he found a contributing factor to this and is working to resolve
